apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  namespace: cert-manager
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.14.2
